"""max_progress achievements

Revision ID: 120911b270f5
Revises: 51f3a1ff6a7f
Create Date: 2014-02-23 15:02:23.496000

"""

# revision identifiers, used by Alembic.
revision = '120911b270f5'
down_revision = '51f3a1ff6a7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('max_progress', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement', 'max_progress')
    ### end Alembic commands ###
