"""added properties

Revision ID: 2c98a8281f2c
Revises: 120911b270f5
Create Date: 2014-03-12 14:13:02.746000

"""

# revision identifiers, used by Alembic.
revision = '2c98a8281f2c'
down_revision = '120911b270f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propdef',
    sa.Column('propdef_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('fieldtype', sa.Enum('string', 'integer', 'float', name='fieldtypes'), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('propdef_id')
    )
    op.create_table('property',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('propdef_id', sa.Integer(), nullable=False),
    sa.Column('value_string', sa.String(length=255), nullable=True),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['propdef_id'], ['propdef.propdef_id'], ),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('gamesession_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamesession_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gamesession_id'], ['game_session.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.property_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'achievement', u'xp')
    op.add_column(u'game_session', sa.Column('public', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'game_session', 'public')
    op.add_column(u'achievement', sa.Column(u'xp', sa.INTEGER(), nullable=True))
    op.drop_table('gamesession_properties')
    op.drop_table('property')
    op.drop_table('propdef')
    ### end Alembic commands ###
