"""userachievement association

Revision ID: 51f3a1ff6a7f
Revises: 6cdad7c41d1
Create Date: 2014-02-23 14:12:44.264000

"""

# revision identifiers, used by Alembic.
revision = '51f3a1ff6a7f'
down_revision = '6cdad7c41d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievement',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('date_unlocked', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.achievement_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.drop_table(u'achievement_user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'achievement_user',
    sa.Column(u'achievement_id', sa.INTEGER(), nullable=True),
    sa.Column(u'user_id', sa.INTEGER(), nullable=True),
    sa.Column(u'progress', sa.INTEGER(), nullable=True),
    sa.Column(u'date_unlocked', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], [u'achievement.achievement_id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.user_id'], )
    )
    op.drop_table('user_achievement')
    ### end Alembic commands ###
