"""initial import

Revision ID: 6cdad7c41d1
Revises: None
Create Date: 2014-02-23 12:09:59.791000

"""

# revision identifiers, used by Alembic.
revision = '6cdad7c41d1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('publisher_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_string_id', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('pwdhash', sa.String(), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('givennames', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('gamecategory',
    sa.Column('gamecategory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('gamecategory_id')
    )
    op.create_table('gamemechanic',
    sa.Column('gamemechanic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('gamemechanic_id')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('yearpublished', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('minplayers', sa.Integer(), nullable=True),
    sa.Column('maxplayers', sa.Integer(), nullable=True),
    sa.Column('recommendedplayers', sa.Integer(), nullable=True),
    sa.Column('playingtime', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('game_gamecategory',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('gamecategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['gamecategory_id'], ['gamecategory.gamecategory_id'], )
    )
    op.create_table('game_publisher',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publisher_id'], )
    )
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_gamemechanic',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('gamemechanic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['gamemechanic_id'], ['gamemechanic.gamemechanic_id'], )
    )
    op.create_table('achievement',
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.PrimaryKeyConstraint('achievement_id')
    )
    op.create_table('user_password_reset',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('game_gameexpansion',
    sa.Column('parent_game_id', sa.Integer(), nullable=True),
    sa.Column('expansion_game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expansion_game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['parent_game_id'], ['game.game_id'], )
    )
    op.create_table('achievement_user',
    sa.Column('achievement_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('date_unlocked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.achievement_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.create_table('gamesession_players',
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamesession_players')
    op.drop_table('achievement_user')
    op.drop_table('game_gameexpansion')
    op.drop_table('user_password_reset')
    op.drop_table('achievement')
    op.drop_table('game_gamemechanic')
    op.drop_table('game_session')
    op.drop_table('game_publisher')
    op.drop_table('game_gamecategory')
    op.drop_table('game')
    op.drop_table('gamemechanic')
    op.drop_table('gamecategory')
    op.drop_table('user')
    op.drop_table('publisher')
    ### end Alembic commands ###
